apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webservice
  namespace: demo-system
  labels:
    app: sample-webservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-webservice
  template:
    metadata:
      labels:
        app: sample-webservice
    spec:
      serviceAccountName: sample-webservice-sa
      containers:
      - name: sample-webservice-container
        image: ghcr.io/krateoplatformops/sample-webservice:0.0.1
        args:
          - "-debug"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: sample-webservice-service
  namespace: demo-system
spec:
  selector:
    app: sample-webservice
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30007
      targetPort: 8081
  type: NodePort
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sample-webservice-viewer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-webservice-viewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sample-webservice-viewer
subjects:
- kind: ServiceAccount
  name: sample-webservice-sa
  namespace: demo-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-webservice-sa
  namespace: demo-system